# from go-ethereum:
name: windows build and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-amd64:
    name: Build windows/amd64
    runs-on: windows-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.26.0
    - name: Check out code
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Get dependencies
      run: go mod download
    - name: Build all broker binaries
      run: |
        go build -v -tags artemis  -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o amc.exe .
        go build -v -tags aws      -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o awsmc.exe .
        go build -v -tags azure    -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o azmc.exe .
        go build -v -tags google   -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o gmc.exe .
        go build -v -tags kafka    -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o kmc.exe .
        go build -v -tags mqtt     -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o mmc.exe .
        go build -v -tags nats     -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o nmc.exe .
        go build -v -tags pulsar   -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o pmc.exe .
        go build -v -tags rabbitmq -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o rmc.exe .
        go build -v -tags redis    -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o redmc.exe .
    - name: Run unit tests
      run: go test -short ./...
